# Cole AQUI o JSON COMPLETO da sua Service Account, igual ao arquivo .json
# Use aspas triplas para preservar quebras de linha da private_key
gcp_service_account = """
{
  "type": "service_account",
  "project_id": "lukma-tv",
  "private_key_id": "266c13a8819e171ab030dc5ce6f043cdd4152bdd",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCU+7G66EqJbVNN\nFTj2ZU68lflteRZV/91+ZRYrxdG4tirOakR5aU1XQm/aEsakd/Tn8Bu+O8eqXvv8\n/sk3RUKxpgFxTzGaPMK83gwsKL2pdye+nrECOV6htA5xVIiO+XqMWs09o706Tg30\nGzI7C9/nwwMCRDBbmVNfC0svzN1MK/8Ru4SeveY9BXlXbVhtjX34JvMtpRJtu36i\nXmRyjNI6YwioWok5JGEE5GMbSOBDPv7bziDCLlz7pt1qrIsH0uI/i+mkOoDOl8yW\nakfoo5bLB+xHjiEabCDtz99ghPARxXasA57dd0L7mn+cA9oLkBLxoK9LUvs7szSI\neZuM/OLBAgMBAAECggEADAHlJy1FpKHdDt9hAerUV7q2qa4SsMe4cFFxYgHFj1+P\nP6es8SQdiaTfIvJUdDj+0hq2AbULuJ2DLbbTPNMmNu8sOpepZcbz4wj6biyybJAf\n8esUVRuOlvXOHDA1+V/+EoXW+NrTi3lzAnOWrs+cMi+zdGFOjHNlFsnwO2AFjff2\nRo2/IXuiAdr7aeJTmxzC2LLIgz4aIyBocIA5+O6eElDC0kwYPV/Sike6cM9heV0C\nc9hXVDwZb5YcVaUfYgtqUkvhxumKHd1vKMua0jPbc8n07c7cvMl+m6wsrg5fa1ST\nxfZnLkDWyarZ3w6pDxO5YwOr9wtzk1M9RFeIO0PDgQKBgQDN8N12WTDky/8I5hUZ\n65rAlp+xVVeR0V81r5e6jzvG8kjKmoBBOtgB+sFBZdMlLw74bll+KYnF4bldwVBI\nTCGibZgNeOvWhRAFyZiOcjHrqEqFdSCp9Lw+eVnJCOttmtonKNjwDzJlT+UXxFDE\nEL3OqxbRroxL+r+oBiFMukDmGQKBgQC5MoIU5oT8Io70z6xPTeCdhCbADOhVnCPk\nGBAdqq3bcs9CEvIZyDTq6K6uI3zLCWeTnhPW0LKpVwR5wq+rjt7jEbmAuQ5yGE9o\nqsI72MxRS8VpjClLi1vGrO9uJvw2e8QYn0TMoRjnoVqy34Z9tfYDMp2wgPwQiWrx\nDIhb3tnm6QKBgCcoLiOrj8VhGEvr24VDK/iEaza/oFfkdHLzwSjCxT3toXOMbuh4\nNMwjjo1NvBjs2q7X5II9iamrYqB1+jrU5uxIZEnjfQwb3tEK5Mvo4J8LL6gyfhRy\nqTxDvJOh84mykNozRRRX/2AOEeQz+ptdB4n9M+iIhLqJodlj2P8Kxv45AoGAQ0tt\nJTcWf5/3HlIQJMkBo3sPsZ1/FwyjphBwWrdYcXNoiHPl8SRkxi9Cuhg/EnAaaPN5\n9gbjxNDP2Ya62rYRm6UnKPUVoLPgtwHFjoWayLelxlKd9stuz+SrI/WalBmpCeFl\n2I15RUHGeVTrw+ZIvKS51BcqgL/OUkThj7CMsXECgYB7Vokbv96o71RdMVbk/VLH\nMaRVbvXXNWd+Y+gBPq9RNQEXp8MEDKy2gF4lKlJAitOaENRRt4bG7PYT+R5M8SAd\nrZK0edBsqX8y1WMHzdxC0H5c+B9Qy8eo18g4dEt4NO+7okiHZnXlO8aTIhxeJBZ/\nmhIxfexa+LhY4HPqECip8Q==\n-----END PRIVATE KEY-----\n",
  "client_email": "lukma-tv-sa@lukma-tv.iam.gserviceaccount.com",
  "client_id": "105263906759479178524",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/lukma-tv-sa%40lukma-tv.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

# ID da sua planilha (entre /d/ e /edit)
GOOGLE_SHEET_ID = "1S5OxNPXB8o4MxX0KM25w5H-c0NBA3OGIdJtegqMlxJk"

